import type { SearchEntry } from "./types";

/**
 * Hand-curated index of every place a portal user might want to jump to.
 * Order within a kind is not significant — the matcher ranks results.
 *
 * Adding a new entry:
 *   1. Pick a stable `id` (kebab-case, kind-prefixed, e.g. "setting-team").
 *   2. Include German + English keywords so bilingual typing works.
 *   3. Gate with `permission` if the destination is permission-protected.
 *      The same `can()` check runs in the dialog (UI) AND, for leads, on
 *      the server route.
 */
export const STATIC_INDEX: SearchEntry[] = [
  // ─── Navigation ────────────────────────────────────────────────────────
  {
    kind: "nav",
    id: "nav-dashboard",
    title: "Übersicht",
    subtitle: "Dashboard · Monatszahlen",
    href: "/dashboard",
    keywords: ["dashboard", "uebersicht", "home", "start", "kennzahlen", "monat"],
    permission: "dashboard.view",
  },
  {
    kind: "nav",
    id: "nav-anfragen",
    title: "Anfragen",
    subtitle: "Patient:innen-Anfragen · Inbox",
    href: "/anfragen",
    keywords: ["anfragen", "leads", "requests", "inbox", "anfrage", "patient"],
    permission: "requests.view",
  },
  {
    kind: "nav",
    id: "nav-auswertung",
    title: "Auswertung",
    subtitle: "Ihre Werbung in Zahlen",
    href: "/auswertung",
    keywords: ["auswertung", "reports", "analytics", "zahlen", "numbers", "performance"],
    permission: "reports.view",
  },
  {
    kind: "nav",
    id: "nav-werbebudget",
    title: "Werbebudget",
    subtitle: "Live-Kampagnen-Budgets",
    href: "/werbebudget",
    keywords: ["werbebudget", "budget", "kampagne", "campaign", "ads", "anzeigen"],
    permission: "campaigns.live",
  },
  {
    kind: "nav",
    id: "nav-fortschritt",
    title: "Fortschritt",
    subtitle: "Onboarding-Meilensteine",
    href: "/fortschritt",
    keywords: ["fortschritt", "progress", "meilenstein", "milestone", "onboarding"],
  },
  {
    kind: "nav",
    id: "nav-medien",
    title: "Medien",
    subtitle: "Videos, Animationen, Grafiken",
    href: "/medien",
    keywords: ["medien", "media", "videos", "animationen", "grafiken", "assets", "downloads"],
    permission: "assets.view",
  },
  {
    kind: "nav",
    id: "nav-bewertungen",
    title: "Bewertungen",
    subtitle: "Google, Jameda · privates Feedback",
    href: "/bewertungen",
    keywords: ["bewertungen", "reviews", "google", "jameda", "sterne", "rating", "feedback"],
    permission: "reviews.view",
  },
  {
    kind: "nav",
    id: "nav-dokumente",
    title: "Dokumente",
    subtitle: "Verträge, AVV, Marketing-Material",
    href: "/dokumente",
    keywords: ["dokumente", "documents", "vertrag", "avv", "dateien", "files"],
    permission: "documents.view.all_roles",
  },
  {
    kind: "nav",
    id: "nav-leitfaden",
    title: "Leitfaden",
    subtitle: "Praxis-Playbook · Gesprächs-Skripte",
    href: "/leitfaden",
    keywords: ["leitfaden", "playbook", "skript", "script", "handbuch", "guide", "anrufe"],
    permission: "leitfaden.view",
  },
  {
    kind: "nav",
    id: "nav-was-waere-wenn",
    title: "Rechner",
    subtitle: "Szenario-Rechner",
    href: "/was-waere-wenn",
    keywords: ["rechner", "was-waere-wenn", "scenario", "simulation", "what if"],
    permission: "tools.what_if",
  },
  {
    kind: "nav",
    id: "nav-feedback",
    title: "Feedback",
    subtitle: "Wünsche & Bugs an EINS",
    href: "/feedback",
    keywords: ["feedback", "wunsch", "bug", "feature", "vorschlag", "idee"],
    permission: "feedback.submit",
  },
  {
    kind: "nav",
    id: "nav-einstellungen",
    title: "Einstellungen",
    subtitle: "Profil, Team, Praxis-Angaben",
    href: "/einstellungen",
    keywords: ["einstellungen", "settings", "config", "konfiguration"],
    permission: "settings.team",
  },

  // ─── Einstellungen — sections + key fields ─────────────────────────────
  {
    kind: "setting",
    id: "setting-profil",
    title: "Mein Profil",
    subtitle: "Einstellungen · Name, E-Mail, Zwei-Faktor",
    href: "/einstellungen#profil",
    keywords: ["profil", "profile", "name", "email", "rolle", "role", "zwei-faktor", "2fa", "mfa"],
  },
  {
    kind: "setting",
    id: "setting-praxis-angaben",
    title: "Praxis-Angaben",
    subtitle: "Einstellungen · Name, leitende Ärztin, HWG-Verantwortliche:r",
    href: "/einstellungen#praxis-angaben",
    keywords: ["praxis", "angaben", "name", "doctor", "aerztin", "arzt", "hwg", "verantwortlich"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-bewertungen",
    title: "Bewertungen & Reputation",
    subtitle: "Einstellungen · Google, Jameda",
    href: "/einstellungen#bewertungen",
    keywords: ["bewertungen", "reputation", "google", "jameda", "review", "reviews", "rezension"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-google-review-url",
    title: "Google-Bewertungs-URL",
    subtitle: "Einstellungen · Bewertungen & Reputation",
    href: "/einstellungen#bewertungen",
    keywords: ["google", "bewertung", "url", "review link", "g.page"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-google-place-id",
    title: "Google Place-ID",
    subtitle: "Einstellungen · Live-Synchronisation",
    href: "/einstellungen#bewertungen",
    keywords: ["google", "place", "place-id", "placeid", "maps", "id"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-jameda-url",
    title: "Jameda-Bewertungs-URL",
    subtitle: "Einstellungen · Bewertungen & Reputation",
    href: "/einstellungen#bewertungen",
    keywords: ["jameda", "bewertung", "url", "rezension"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-review-request",
    title: "Bewertungs-Anfragen aktivieren",
    subtitle: "Einstellungen · Bewertungen & Reputation",
    href: "/einstellungen#bewertungen",
    keywords: ["bewertung", "anfrage", "aktivieren", "review request", "patient", "email"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-review-sync",
    title: "Jetzt synchronisieren · Bewertungen",
    subtitle: "Einstellungen · Live-Synchronisation",
    href: "/einstellungen#bewertungen",
    keywords: ["sync", "synchronisieren", "bewertungen", "aktualisieren", "refresh"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-team",
    title: "Team",
    subtitle: "Einstellungen · Mitglieder einladen & verwalten",
    href: "/einstellungen#team",
    keywords: ["team", "mitglied", "member", "einladung", "invite", "rolle", "role"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-werbekonten",
    title: "Werbekonten verbinden",
    subtitle: "Einstellungen · Meta, Google Ads",
    href: "/einstellungen#werbekonten",
    keywords: ["werbekonto", "ads", "meta", "facebook", "instagram", "google", "verbinden", "oauth"],
    permission: "settings.integrations",
  },
  {
    kind: "setting",
    id: "setting-behandlungen",
    title: "Behandlungs-Kategorien",
    subtitle: "Einstellungen · Treatments & Folgetermine",
    href: "/einstellungen#behandlungen",
    keywords: ["behandlung", "treatment", "kategorie", "stichwort", "keyword", "folgetermin", "recall"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-standorte",
    title: "Standorte",
    subtitle: "Einstellungen · Praxis-Adressen",
    href: "/einstellungen#standorte",
    keywords: ["standort", "location", "adresse", "address", "filiale"],
    permission: "settings.team",
  },
  {
    kind: "setting",
    id: "setting-reputation-snapshot",
    title: "Reputation-Momentaufnahme",
    subtitle: "Einstellungen · Bewertung manuell erfassen",
    href: "/einstellungen#reputation",
    keywords: ["reputation", "snapshot", "momentaufnahme", "bewertung", "manuell"],
    permission: "reviews.manage",
  },
  {
    kind: "setting",
    id: "setting-audit",
    title: "Audit-Log",
    subtitle: "Einstellungen · letzte 20 Aktionen",
    href: "/einstellungen#audit",
    keywords: ["audit", "log", "aktionen", "history", "verlauf", "aenderungen"],
    permission: "audit.view",
  },
  {
    kind: "setting",
    id: "setting-make",
    title: "Make.com-Anbindung",
    subtitle: "Einstellungen · Webhook · HMAC-Geheimnis",
    href: "/einstellungen#bewertungen",
    keywords: ["make", "webhook", "integration", "hmac", "secret", "geheimnis", "automation"],
    permission: "settings.integrations",
  },

  // ─── Leitfaden — section headings ──────────────────────────────────────
  {
    kind: "leitfaden",
    id: "leitfaden-prinzipien",
    title: "Goldene Prinzipien",
    subtitle: "Leitfaden · Grundregeln am Telefon",
    href: "/leitfaden#prinzipien",
    keywords: ["prinzip", "principle", "regel", "rule", "golden", "anerkennen", "termin"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-kpi",
    title: "KPI-Ziele für jeden Anruf",
    subtitle: "Leitfaden · Reaktionszeit, Abschlussquote, No-Show",
    href: "/leitfaden#kpi",
    keywords: ["kpi", "ziel", "goal", "reaktionszeit", "response", "abschluss", "conversion", "no-show"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-vorbereitung",
    title: "Vor jedem Anruf in 30 Sekunden",
    subtitle: "Leitfaden · Vorbereitungs-Checkliste",
    href: "/leitfaden#vorbereitung",
    keywords: ["vorbereitung", "prep", "anruf", "call", "30 sekunden", "checkliste"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-eroeffnung",
    title: "Gesprächs-Eröffnung, wortwörtlich",
    subtitle: "Leitfaden · Standard-Skript",
    href: "/leitfaden#eroeffnung",
    keywords: ["eroeffnung", "opening", "skript", "script", "anruf", "begruessung", "wortwoertlich"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-discovery",
    title: "Discovery: 14 Fragen in vier Blöcken",
    subtitle: "Leitfaden · Bedarfs-Analyse",
    href: "/leitfaden#discovery",
    keywords: ["discovery", "fragen", "questions", "bedarf", "interesse", "budget", "vertrauen"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-einwand",
    title: "Einwandbehandlung",
    subtitle: "Leitfaden · 23 Patienten-Einwände",
    href: "/leitfaden#einwand",
    keywords: ["einwand", "objection", "teuer", "preis", "price", "zu teuer", "antwort"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-hwg",
    title: "HWG-Quick-Reference",
    subtitle: "Leitfaden · Sag-So / Sag-So-Nicht",
    href: "/leitfaden#hwg",
    keywords: ["hwg", "heilmittelwerbegesetz", "compliance", "sag-so", "verboten", "erlaubt"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-no-show",
    title: "No-Show-Prävention",
    subtitle: "Leitfaden · Cadence + Erinnerungen",
    href: "/leitfaden#no-show",
    keywords: ["no-show", "praevention", "prevention", "sms", "email", "erinnerung", "cadence"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-vermeiden",
    title: "Was Sie unbedingt vermeiden",
    subtitle: "Leitfaden · Typische Fehler",
    href: "/leitfaden#vermeiden",
    keywords: ["vermeiden", "avoid", "fehler", "mistake", "rote flagge", "red flag"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-recht",
    title: "Rechtsgrundlagen, kompakt",
    subtitle: "Leitfaden · HWG, MBO-Ä, DSGVO, BGB",
    href: "/leitfaden#recht",
    keywords: ["recht", "law", "hwg", "mbo", "dsgvo", "bgb", "rechtlich", "compliance"],
    permission: "leitfaden.view",
  },
  {
    kind: "leitfaden",
    id: "leitfaden-quiz",
    title: "Leitfaden-Prüfung starten",
    subtitle: "Leitfaden · Quiz für Mitarbeiter:innen",
    href: "/leitfaden/pruefung",
    keywords: ["quiz", "pruefung", "test", "exam", "schulung"],
    permission: "leitfaden.quiz",
  },

  // ─── Dashboard KPIs ────────────────────────────────────────────────────
  {
    kind: "kpi",
    id: "kpi-qualifizierte-anfragen",
    title: "Qualifizierte Anfragen",
    subtitle: "Dashboard · Monatszahl",
    href: "/dashboard",
    keywords: ["qualifizierte", "anfragen", "leads", "qualified", "monat", "month"],
    permission: "dashboard.view",
  },
  {
    kind: "kpi",
    id: "kpi-umsatz",
    title: "Umsatz in diesem Monat",
    subtitle: "Dashboard · Monatszahl",
    href: "/dashboard",
    keywords: ["umsatz", "revenue", "geld", "einnahmen", "euro", "ertrag"],
    permission: "dashboard.view",
  },
  {
    kind: "kpi",
    id: "kpi-offene-anfragen",
    title: "Offene Anfragen",
    subtitle: "Dashboard · SLA-Status",
    href: "/dashboard",
    keywords: ["offen", "open", "anfragen", "sla", "ueberfaellig", "breach"],
    permission: "dashboard.view",
  },
  {
    kind: "kpi",
    id: "kpi-reaktion",
    title: "Anfragen-Reaktion",
    subtitle: "Dashboard · SLA-Ampel",
    href: "/dashboard",
    keywords: ["reaktion", "response", "antwortzeit", "sla", "ampel"],
    permission: "dashboard.view",
  },
  {
    kind: "kpi",
    id: "kpi-werbeertrag",
    title: "Werbeertrag (ROAS)",
    subtitle: "Dashboard · Anzeigen-Effizienz",
    href: "/dashboard",
    keywords: ["werbeertrag", "roas", "return on ad spend", "anzeigen", "ads", "effizienz"],
    permission: "dashboard.view",
  },
  {
    kind: "kpi",
    id: "kpi-heute",
    title: "Heute neu eingegangen",
    subtitle: "Dashboard · 24-h-Indikator",
    href: "/dashboard",
    keywords: ["heute", "today", "neu", "new", "24h", "eingang"],
    permission: "dashboard.view",
  },
  {
    kind: "kpi",
    id: "kpi-patientenfeedback",
    title: "Patientenfeedback",
    subtitle: "Dashboard · 30-Tage-Übersicht",
    href: "/bewertungen/feedback",
    keywords: ["patientenfeedback", "feedback", "bewertung", "klicks", "rate"],
    permission: "stimme.view",
  },

  // ─── Auswertung ────────────────────────────────────────────────────────
  {
    kind: "auswertung",
    id: "auswertung-trichter",
    title: "Trichter · Anfrage → Termin → Behandlung",
    subtitle: "Auswertung · Funnel-Quoten",
    href: "/auswertung",
    keywords: ["trichter", "funnel", "anfrage", "termin", "beratung", "behandlung", "conversion"],
    permission: "reports.view",
  },
  {
    kind: "auswertung",
    id: "auswertung-quellen",
    title: "Attribution nach Quelle",
    subtitle: "Auswertung · Google / Meta / Organic",
    href: "/auswertung",
    keywords: ["quelle", "source", "attribution", "google", "meta", "organic", "direkt"],
    permission: "reports.view",
  },
  {
    kind: "auswertung",
    id: "auswertung-kanal",
    title: "Attribution nach Kanal",
    subtitle: "Auswertung · Paid / Display / Social",
    href: "/auswertung",
    keywords: ["kanal", "channel", "paid", "display", "social", "organic"],
    permission: "reports.view",
  },
  {
    kind: "auswertung",
    id: "auswertung-kampagnen",
    title: "Top-Kampagnen",
    subtitle: "Auswertung · Beste Anzeigen-Kampagnen",
    href: "/auswertung",
    keywords: ["kampagne", "campaign", "top", "anzeige", "ads"],
    permission: "reports.view",
  },
  {
    kind: "auswertung",
    id: "auswertung-heatmap",
    title: "Wochentag- & Uhrzeit-Heatmap",
    subtitle: "Auswertung · Wann kommen Anfragen rein",
    href: "/auswertung",
    keywords: ["heatmap", "wochentag", "uhrzeit", "weekday", "hour", "zeit", "verteilung"],
    permission: "reports.view",
  },
  {
    kind: "auswertung",
    id: "auswertung-response-time",
    title: "Antwortzeit-Verteilung",
    subtitle: "Auswertung · Median / P95 / P99",
    href: "/auswertung",
    keywords: ["antwortzeit", "response time", "median", "p95", "p99", "sla"],
    permission: "reports.view",
  },
  {
    kind: "auswertung",
    id: "auswertung-staff",
    title: "Mitarbeiter-Leistung",
    subtitle: "Auswertung · Performance pro Person",
    href: "/auswertung",
    keywords: ["mitarbeiter", "staff", "team", "leistung", "performance", "person"],
    permission: "reports.view",
  },
  {
    kind: "auswertung",
    id: "auswertung-cohort",
    title: "Patient:innen-Kohorten",
    subtitle: "Auswertung · Retention nach Akquise-Monat",
    href: "/auswertung",
    keywords: ["kohorte", "cohort", "retention", "patient", "akquise"],
    permission: "reports.view",
  },
  {
    kind: "auswertung",
    id: "auswertung-ltv",
    title: "Top-Patient:innen nach LTV",
    subtitle: "Auswertung · Lifetime Value",
    href: "/auswertung",
    keywords: ["ltv", "lifetime value", "patient", "top", "umsatz pro patient"],
    permission: "reports.view",
  },
  {
    kind: "auswertung",
    id: "auswertung-reviews",
    title: "Bewertungs-Trend",
    subtitle: "Auswertung · Google / Jameda",
    href: "/auswertung",
    keywords: ["bewertung", "review", "trend", "google", "jameda"],
    permission: "reports.view",
  },
];
